### ISSUE TITLE
Support for COPY FROM STDIN

### ISSUE THREAD

**Issue by rliebz** [DerekStride/tree-sitter-sql#256]
For example:

```sql
COPY some_table (a, b, c) FROM STDIN (FORMAT CSV);
1,2,3
d,e,f
\.
```

The actual data used in my situation is massive, and it causes the parsing to take a very long time (over a minute to open the file in neovim). I assume it would be much more efficient if the parser didn't attempt to parse the CSV data as SQL. 

I believe the ideal behavior would be to treat the data in between the `;` and `\.` as `csv` if the format is explicitly CSV, and text otherwise. Parsing other components of the `COPY` statement would be nice, but for me personally, handling the data contents would be the biggest win. 

Ref: https://www.postgresql.org/docs/current/sql-copy.html

**Comment by matthias-Q** [comment]
Hmm, ok, first we should parse this statement at all. :-) I can take a look

**Comment by matthias-Q** [comment]
I have to ask. When checking the postgres documentation, there is no CSV part in the query. As the name suggests it is provided by stdin input. So the Parser would only parse everything before the ; anyways. Not sure how to handle that, because it is not part of the spec.

**Comment by rliebz** [comment]
If you execute the SQL as a file, once you terminate the `COPY` statement, it treats the next section of the file as STDIN until the end-of-data.

To verify, you can put this in a file called `tmp.sql`:

```sql
BEGIN; 

CREATE TEMPORARY TABLE my_table (
  id   TEXT,
  num  INT
);

COPY my_table (id, num) FROM STDIN (FORMAT CSV);
a,1
b,2
c,3
\.

SELECT * from my_table;

ROLLBACK;
```

Then with whatever DB set up you need:

```console
$ psql -f tmp.sql
BEGIN
CREATE TABLE
COPY 3
 id | num 
----+-----
 a  |   1
 b  |   2
 c  |   3
(3 rows)

ROLLBACK

```

**Comment by matthias-Q** [comment]
Yes, I understand. But it seems to be not documented. I have 2 suggestions: first would be to call it via `cat data.csv | psql -f query.sql` or to specify the file in your SQL statement (`FROM <filename>` instead of `FROM STDIN`)
I don't know if these would be a reasonable workarounds.

The issue is, that we finish the query after an optional `;`. If we want to parse the "data block" as well, we would have to put that very close to the root of the tree. I think this would make the parser really slow.

**Comment by matthias-Q** [comment]
I have implemented the SQL part for now and left out the "data" part. I have tried adding it, but it just created a bunch of problems. It gets even more complicated when ';' is the separator in the CSV block.

**Comment by DerekStride** [comment]
> The actual data used in my situation is massive, and it causes the parsing to take a very long time (over a minute to open the file in neovim).

It'd be helpful to know the baseline performance of neovim opening the file. Can you uninstall the sql parse and then time how long it takes to open the file?

The other metric would be how long does it take when syntax highlighting is disabled completely (e.g. add `syntax off` to your config).

I'm asking because I want to know the impact that the sql parser is having on performance and if implementing special cases for the data block will actually help.

**Comment by rliebz** [comment]
I'm not sure what the proper way to benchmark this is, so I just started a stopwatch after opening the file and stopped it when the first character appeared on the screen. Happy to re-run it if there's a more precise thing I can be doing. 

- With `syntax off`, parser uninstalled: instant
- With `syntax on`, parser uninstalled: instant
- With `syntax off`, parser installed, highlight enabled: 1m38s
- With `syntax on`, parser installed, highlight enabled: 1m33s

Also fully acknowledging that this is a 47,000 line CSV embedded in this SQL file, so I'm probably not a particularly representative use case. Chopping that roughly in half gets me down to ~16s (and chopping the other half also gets to ~16s, so it's probably more about size than contents).

**Comment by matthias-Q** [comment]
You could disable treesitter for large files:
```lua
opts = {
    highlight = {
        disable = function(lang, buf)
            local max_filesize = 100 * 1024 -- 100 KB
            local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(buf))
            if ok and stats and stats.size > max_filesize then
                return true
            end
        end,
    },
```
This should be part of your Treesitter configuration.

**Comment by rliebz** [comment]
I might be missing something, but even if I explicitly disable highlighting and all other modules by setting `enabled` to `false` in each, I'm still experiencing the delay. Disabling highlighting doesn't solve the issue (and I can confirm it's disabled by the visual difference). Only thing that fixes it is uninstalling the parser.
